version: "3"
services:

  wingman:
    build:
        context: .
        args:
          CMD: ./cmd/api
          VER: local

  vault:
    image: hashicorp/vault
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    ports:
      - 8200:8200

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
      - listen_addresses='*'
    ports:
      - 5432:5432

  wait:
    image: dadarek/wait-for-dependencies
    depends_on:
      - vault
      - postgres
    command: vault:8200 postgres:5432
