version: "3"
services:

  postgres:
    container_name: wingman_postgres
    image: postgres
    environment:
      - POSTGRES_DB=wingman
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
      - listen_addresses='*'
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d wingman" ]
      interval: 10s
      timeout: 20s
      retries: 3

  migrations:
    container_name: wingman_migration
    build: migrations
    entrypoint: "/bin/bash -c 'while ! (echo > /dev/tcp/postgres/5432) > /dev/null 2>&1; do sleep 1; done; /flyway/flyway migrate'"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/wingman
      - FLYWAY_USER=admin
      - FLYWAY_PASSWORD=pass
