package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.60

import (
	"context"

	"github.com/bigmikesolutions/wingman/graphql/model"
)

// Database is the resolver for the database field.
func (r *environmentResolver) Database(ctx context.Context, obj *model.Environment, id string) (*model.Database, error) {
	// TODO implement this stub
	return &model.Database{
		ID: id,
	}, nil
}
