package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.60

import (
	"context"
	"log"

	"github.com/bigmikesolutions/wingman/graphql/generated"
	"github.com/bigmikesolutions/wingman/graphql/model"
)

// EnvGrant is the resolver for the envGrant field.
func (r *mutationResolver) EnvGrant(ctx context.Context, input model.EnvGrantInput) (*model.EnvGrantPayload, error) {
	// TODO implement this
	log.Printf("Env grant mutation...")
	return &model.EnvGrantPayload{
		MutationID: input.MutationID,
	}, nil
}

// Environment is the resolver for the environment field.
func (r *queryResolver) Environment(ctx context.Context, id string) (*model.Environment, error) {
	// TODO implement this stub
	return &model.Environment{
		ID: id,
	}, nil
}

// Environment returns generated.EnvironmentResolver implementation.
func (r *Resolver) Environment() generated.EnvironmentResolver { return &environmentResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// ResourceGrantInput returns generated.ResourceGrantInputResolver implementation.
func (r *Resolver) ResourceGrantInput() generated.ResourceGrantInputResolver {
	return &resourceGrantInputResolver{r}
}

type (
	environmentResolver        struct{ *Resolver }
	mutationResolver           struct{ *Resolver }
	queryResolver              struct{ *Resolver }
	resourceGrantInputResolver struct{ *Resolver }
)

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *Resolver) EnvGrantPayload() generated.EnvGrantPayloadResolver {
	return &envGrantPayloadResolver{r}
}
type envGrantPayloadResolver struct{ *Resolver }
*/
