package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	"github.com/bigmikesolutions/wingman/graphql/generated"
	"github.com/bigmikesolutions/wingman/graphql/model"
)

// UserRoles is the resolver for the userRoles field.
func (r *userRoleBindingResolver) UserRoles(ctx context.Context, obj *model.UserRoleBinding) ([]*model.UserRole, error) {
	panic(fmt.Errorf("not implemented: UserRoles - userRoles"))
}

// UserRoleBinding returns generated.UserRoleBindingResolver implementation.
func (r *Resolver) UserRoleBinding() generated.UserRoleBindingResolver {
	return &userRoleBindingResolver{r}
}

type userRoleBindingResolver struct{ *Resolver }
