package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	"github.com/bigmikesolutions/wingman/graphql/generated"
	"github.com/bigmikesolutions/wingman/graphql/model"
)

// AddUserRoleBinding is the resolver for the addUserRoleBinding field.
func (r *mutationResolver) AddUserRoleBinding(ctx context.Context, input model.AddUserRoleBindingInput) (*model.AddUserRoleBindingPayload, error) {
	panic(fmt.Errorf("not implemented: AddUserRoleBinding - addUserRoleBinding"))
}

// AddK8sUserRole is the resolver for the addK8sUserRole field.
func (r *mutationResolver) AddK8sUserRole(ctx context.Context, input model.AddK8sUserRoleInput) (*model.AddK8sUserRolePayload, error) {
	panic(fmt.Errorf("not implemented: AddK8sUserRole - addK8sUserRole"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Environment is the resolver for the environment field.
func (r *queryResolver) Environment(ctx context.Context, id string) (*model.Environment, error) {
	panic(fmt.Errorf("not implemented: Environment - environment"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
